# Composes multiple augmentations into a single pipeline
_target_: cybench.models.torch.utils.augmentation.AugmentationComposer
augmentations:
  - _target_: cybench.models.torch.utils.augmentation.TimeSeriesClipping
    start: 10
    end: 10

  - _target_: cybench.models.torch.utils.augmentation.GaussianNoiseTimeSeries
    std: 0.02

  - _target_: cybench.models.torch.utils.augmentation.YearUniformNoise
    noise_range: 0.15