_target_: cybench.models.torch.utils.augmentation.AugmentationComposer

augmentations:
  #time_clipping:
    #_target_: cybench.models.torch.utils.augmentation.TimeSeriesClipping
    #start: 0
    #end: 30
    #_search_:
    #  start:
    #    type: int
    #    low: 0
    #    high: 30
    #    step: 10
    #  end:
    #    type: int
    #    low: 0
    #    high: 30
    #    step: 10

  gaussian_noise:
    _target_: cybench.models.torch.utils.augmentation.GaussianNoiseTimeSeries
    std: 0.01
    #_search_:
    #  std:
    #    type: float
    #    low: 1e-3
    #    high: 0.1
    #    log: true

  year_noise:
    _target_: cybench.models.torch.utils.augmentation.YearUniformNoise
    noise_range: 0.3
    #_search_:
    #  noise_range:
    #    type: float
    #    low: 0.00
     #   high: 0.3