defaults:
  - torch_model: late_fusion_network
  - optimizer: adamw
  - augmentation: extensive
  - scheduler: cosine_warmup
  - early_stopping: val
  - override torch_model/temporal_encoder/processor: cnn # overriding the default processor to cnn
  - _self_

# Root-level trainer configuration
_target_: cybench.models.torch.trainer.TorchTrainer
name: cnn_lf  # Updated name for logging/tracking
framework: torch
epochs: 100
seed: ${experiment.seed}
device: ${experiment.device}
verbose: true
_search_:
  epochs:
    type: int
    low: 25
    high: 100
    step: 25

# data loader configuration
dataloader:
  _target_: torch.utils.data.DataLoader
  _partial_: true
  batch_size: 64
  shuffle: True
  _search_:
    batch_size:
      type: int
      low: 32
      high: 128
      step: 32

# Further overwriting the default torch model
torch_model:
  temporal_encoder:
    # attention pooling works great for cnn to determine important features along the time series
    pooling:
      _target_: cybench.models.torch.model_components.temporal_encoder.AttentionPooling
      # We must define arguments that weren't in LastStepPooling
      embed_dim: ${model.torch_model.embed_dim}