defaults:
  - torch_model: late_fusion_network
  - optimizer: adamw
  - augmentation: all
  - scheduler: cosine
  - _self_

# Root-level trainer configuration
_target_: cybench.models.torch.trainer.TorchTrainer
name: lstm_lf
epochs: 100
seed: ${experiment.seed}
device: ${experiment.device}
verbose: true

# data loader configuration
dataloader:
  _target_: torch.utils.data.DataLoader
  _partial_: true
  batch_size: 32
  shuffle: True
