defaults:
  - torch_model: late_fusion_network
  - optimizer: adamw
  - augmentation: extensive
  - scheduler: cosine_warmup
  - _self_

# Root-level trainer configuration
_target_: cybench.models.torch.trainer.TorchTrainer
name: lstm_lf
framework: torch
epochs: 100
seed: ${experiment.seed}
device: ${experiment.device}
verbose: true
_search_:
  epochs:
    type: int
    low: 25
    high: 100
    step: 25

# data loader configuration
dataloader:
  _target_: torch.utils.data.DataLoader
  _partial_: true
  batch_size: 64
  shuffle: True
  _search_:
    batch_size:
      type: int
      low: 32
      high: 128
      step: 32
