_target_: cybench.models.torch.model_components.temporal_encoder.TransformerProcessor

embed_dim: ${model.torch_model.embed_dim}

num_layers: 4        # number of TransformerEncoder layers
nhead: 4             # attention heads
dim_feedforward: 256 # FFN hidden size
dropout: 0.1