defaults:
  - fusion: gated
  - temporal_encoder: temporal_encoder
  - _self_

_target_: cybench.models.torch.architectures.late_fusion_network.LateFusionNetwork

context_in_dim: ???
temporal_in_dim: ???
embed_dim: 128

context_encoder:
  _target_: cybench.models.torch.model_components.context_encoder.ContextEncoder
  in_dim: ${model.torch_model.context_in_dim}
  hidden_dims:
    - ${model.torch_model.embed_dim}
  embed_dim: ${model.torch_model.embed_dim}
  dropout: 0.2

regression_head:
  _target_: cybench.models.torch.model_components.head.RegressionHead
  hidden_dims:
    - ${model.torch_model.embed_dim}
    - ${model.torch_model.embed_dim}
  dropout: 0.2
