#!/usr/bin/env python3
"""Build benchmark_jobs.txt from DATASETS × models.

Skips crop/country pairs when the data directory is missing or when yield years
cannot support the fixed screening split (5-last test + 2-last val).
"""

from __future__ import annotations

import argparse
from pathlib import Path

import cybench.config as config
from cybench.config import DATASETS
from cybench.models.baseline_csv_paths import lpjml_csv_path, twso_csv_path
from cybench.runs.slurm.benchmark_completion_lib import (
    JobRow,
    check_screening_years,
    load_yield_years,
)

SLURM_DIR = Path(__file__).resolve().parent
MODELS_FILE = SLURM_DIR / "models.txt"
DEFAULT_OUT = SLURM_DIR / "benchmark_jobs.txt"


def _read_models(path: Path) -> list[tuple[str, str, str, str, str]]:
    rows: list[tuple[str, str, str, str, str]] = []
    for line in path.read_text().splitlines():
        line = line.split("#", 1)[0].strip()
        if not line:
            continue
        parts = line.split()
        if len(parts) != 5:
            raise ValueError(f"Expected 5 columns in {path}: {line!r}")
        rows.append(tuple(parts))  # type: ignore[arg-type]
    return rows



def build_jobs(
    *,
    crops: list[str],
    countries: list[str] | None,
    models_path: Path,
    data_dir: Path | None = None,
    model_filter: list[str] | None = None,
) -> list[JobRow]:
    """Return manifest rows for crop/country pairs with data and enough yield years."""
    models = _read_models(models_path)
    if model_filter:
        allowed = {name.lower() for name in model_filter}
        models = [row for row in models if row[0].lower() in allowed]

    root = Path(data_dir or config.PATH_DATA_DIR)
    jobs: list[JobRow] = []
    for crop in crops:
        if crop not in DATASETS:
            raise ValueError(f"Unknown crop {crop!r}. Choose from {list(DATASETS)}")
        cn_list = countries if countries else DATASETS[crop]
        for country in cn_list:
            if country not in DATASETS[crop]:
                if countries is not None:
                    continue
                raise ValueError(f"Country {country!r} not in DATASETS[{crop!r}]")
            if not (root / crop / country).is_dir():
                continue
            years = load_yield_years(crop, country, data_dir=root)
            ok_years, _years_reason = check_screening_years(years)
            if not ok_years:
                continue
            for model, framework, hp_search, feature_design, needs_gpu in models:
                if model == "lpjml_bc" and not lpjml_csv_path(
                    crop, country, data_dir=root
                ).is_file():
                    continue
                if model == "twso_bc" and not twso_csv_path(
                    crop, country, data_dir=root
                ).is_file():
                    continue
                jobs.append(
                    JobRow(
                        crop=crop,
                        country=country,
                        model=model,
                        framework=framework,
                        hp_search=hp_search,
                        feature_design=feature_design,
                        needs_gpu=needs_gpu,
                    )
                )
    return jobs


def generate(
    *,
    crops: list[str],
    countries: list[str] | None,
    models_path: Path,
    output: Path,
    data_dir: Path | None = None,
) -> int:
    jobs = build_jobs(
        crops=crops,
        countries=countries,
        models_path=models_path,
        data_dir=data_dir,
    )
    lines: list[str] = [
        "# crop country model framework hp_search feature_design needs_gpu",
        "# Generated by generate_job_manifest.py — edit or regenerate as needed.",
    ]
    lines.extend(job.to_line() for job in jobs)
    output.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {len(jobs)} jobs to {output}")
    return len(jobs)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--crops",
        nargs="+",
        default=["maize", "wheat"],
        help="Crops to include (default: maize wheat)",
    )
    parser.add_argument(
        "--countries",
        nargs="*",
        default=None,
        help="Optional country filter (default: all with data on disk)",
    )
    parser.add_argument("--models", type=Path, default=MODELS_FILE)
    parser.add_argument("-o", "--output", type=Path, default=DEFAULT_OUT)
    args = parser.parse_args()
    generate(
        crops=args.crops,
        countries=args.countries or None,
        models_path=args.models,
        output=args.output,
    )


if __name__ == "__main__":
    main()
