#!/usr/bin/env python3
"""Build benchmark_jobs.txt from DATASETS × models.

Skips crop/country pairs when the data directory is missing or when yield years
cannot support the fixed screening split (5-last test + 2-last val).
"""

from __future__ import annotations

import argparse
from pathlib import Path

import cybench.config as config
from cybench.config import DATASETS
from cybench.models.lpjml_model import lpjml_csv_path
from cybench.models.twso_model import twso_csv_path
from cybench.runs.slurm.benchmark_completion_lib import (
    check_screening_years,
    load_yield_years,
)

SLURM_DIR = Path(__file__).resolve().parent
MODELS_FILE = SLURM_DIR / "models.txt"
DEFAULT_OUT = SLURM_DIR / "benchmark_jobs.txt"


def _read_models(path: Path) -> list[tuple[str, str, str, str, str]]:
    rows: list[tuple[str, str, str, str, str]] = []
    for line in path.read_text().splitlines():
        line = line.split("#", 1)[0].strip()
        if not line:
            continue
        parts = line.split()
        if len(parts) != 5:
            raise ValueError(f"Expected 5 columns in {path}: {line!r}")
        rows.append(tuple(parts))  # type: ignore[arg-type]
    return rows



def generate(
    *,
    crops: list[str],
    countries: list[str] | None,
    models_path: Path,
    output: Path,
) -> int:
    models = _read_models(models_path)
    data_dir = Path(config.PATH_DATA_DIR)
    lines: list[str] = [
        "# crop country model framework hp_search feature_design needs_gpu",
        "# Generated by generate_job_manifest.py — edit or regenerate as needed.",
    ]
    n = 0
    skipped_years: list[str] = []
    skipped_lpjml: list[str] = []
    skipped_twso: list[str] = []
    for crop in crops:
        if crop not in DATASETS:
            raise ValueError(f"Unknown crop {crop!r}. Choose from {list(DATASETS)}")
        cn_list = countries if countries else DATASETS[crop]
        for country in cn_list:
            if country not in DATASETS[crop]:
                if countries is not None:
                    continue
                raise ValueError(f"Country {country!r} not in DATASETS[{crop!r}]")
            if not (data_dir / crop / country).is_dir():
                continue
            years = load_yield_years(crop, country)
            ok_years, years_reason = check_screening_years(years)
            if not ok_years:
                skipped_years.append(f"{crop}/{country} ({years_reason})")
                continue
            for model, framework, hp_search, feature_design, needs_gpu in models:
                if model == "lpjml_bc" and not lpjml_csv_path(
                    crop, country, data_dir=data_dir
                ).is_file():
                    skipped_lpjml.append(f"{crop}/{country}")
                    continue
                if model == "twso_bc" and not twso_csv_path(
                    crop, country, data_dir=data_dir
                ).is_file():
                    skipped_twso.append(f"{crop}/{country}")
                    continue
                lines.append(
                    f"{crop} {country} {model} {framework} {hp_search} {feature_design} {needs_gpu}"
                )
                n += 1
    output.write_text("\n".join(lines) + "\n")
    print(f"Wrote {n} jobs to {output}")
    for note in skipped_years:
        print(f"Skipped {note} — too few yield years for screening split")
    for note in skipped_lpjml:
        print(f"Skipped {note} — no lpjml_*.csv (run data_preparation/prepare_lpjml_data.py)")
    for note in skipped_twso:
        print(f"Skipped {note} — no twso_*.csv")
    return n


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--crops",
        nargs="+",
        default=["maize", "wheat"],
        help="Crops to include (default: maize wheat)",
    )
    parser.add_argument(
        "--countries",
        nargs="*",
        default=None,
        help="Optional country filter (default: all with data on disk)",
    )
    parser.add_argument("--models", type=Path, default=MODELS_FILE)
    parser.add_argument("-o", "--output", type=Path, default=DEFAULT_OUT)
    args = parser.parse_args()
    generate(
        crops=args.crops,
        countries=args.countries or None,
        models_path=args.models,
        output=args.output,
    )


if __name__ == "__main__":
    main()
