defaults:
  - _self_
  - target: yield
  - non_temporal: no_transform
  - temporal: no_aggregate

# set crop and country | optionally: set multiple countries such as in europe.yaml
crop: maize
country: FR

# name will show in experiment name
name: ${dataset.crop}_${dataset.country}

# years to be considered
min_year: 2000
max_year: 2023

# set the framework of the data stored | optionally:
# pandas - creates Dataset instance ready for tabular frameworks such as Sklearn or XGBoost. Call: X, y = dataset.make_X_y()
# torch  - creates TorchDataset - a wrapper for compatibility with torch DataLoader objects
framework: torch