
_target_: cybench.models.torch.model_components.temporal_encoder.ConvTokenizer

in_dim: ${model.torch_model.temporal_in_dim}
embed_dim: ${model.torch_model.embed_dim}

use_seasonal_embedding: false

# patch embeddings
# for simplicity the window size is equal the patch size
patch_size: 7

# Search space for hyperparameter tuning
_search_:
  patch_size:
    type: int
    low: 1
    high: 9
    step: 2