_target_: cybench.models.torch.model_components.hf_temporal_encoder.InformerTemporalEncoder

in_dim: ${model.torch_model.temporal_in_dim}
embed_dim: ${model.torch_model.embed_dim}
seq_len: ???
d_model: 64
num_attention_heads: 4
ffn_dim: 256
num_layers: 3
dropout: 0.1

_search_:
  d_model:
    type: int
    low: 64
    high: 128
    step: 64
  num_layers:
    type: int
    low: 2
    high: 4
