defaults:
  - processor: lstm  # cnn / lstm / transformer
  - tokenizer: patch_conv

_target_: cybench.models.torch.model_components.temporal_encoder.TemporalEncoder

pooling:
  _target_: cybench.models.torch.model_components.temporal_encoder.LastStepPooling

embed_dim: ${model.torch_model.embed_dim}