_target_: cybench.models.torch.model_components.fusion.GatedFusion

# temporal_dim and static_dim supplied at runtime from code.

temporal_dim: ${model.torch_model.embed_dim}
static_dim: ${model.torch_model.embed_dim}
out_dim: ${model.torch_model.embed_dim}
dropout: 0.0
use_layernorm: true
